[project]
name = "w17-mlops"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "evidently>=0.7.23",
    "fastapi>=0.141.1",
    "matplotlib>=3.11.2",
    "mlflow>=3.16.1",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "uvicorn>=0.53.0",
    "xgboost>=3.4.1",
]
